# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='GPLv3'

[[mods]]
modId="adomnia"
version="${file.jarVersion}"
displayName="AdOmnia"
credits=""
authors="Quarris, dooZyz"
description='''

'''
[[dependencies.adomnia]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.adomnia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
